services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
